kind: Service
apiVersion: v1
metadata:
  name: acme-controller
spec:
  selector:
    app: acme-controller
  clusterIP: None
  ports:
  - name: http
    protocol: TCP 
    port: 80
    targetPort: 5000
